# Generated by Django 2.2.16 on 2022-04-09 22:57

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(help_text='Описание', validators=[users.validators.validate_not_empty], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Почта пользователя', max_length=254, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False, help_text='Ответ', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Имя пользователя', max_length=100, validators=[users.validators.validate_not_empty], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Объект', max_length=100, verbose_name='Объект'),
        ),
    ]
